# --- Build stage ---
FROM node:20-bullseye

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /server

COPY package.json package-lock.json ./
COPY /prisma/schema.prisma ./

RUN npm ci

COPY src /server/src
COPY tsconfig.json /server/

# RUN npm run build

EXPOSE 5001
EXPOSE 40000-40050/udp

CMD ["npm", "run", "dev"]
